# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc "Dynamic versioned controlled remote marketplace for local / CI environments"
  homepage "https://ZachiNachshon.github.io/anchor/"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.3.0/anchor_0.3.0_Darwin_arm64.tar.gz"
      sha256 "fd0feef5dd1a87eafcb4580edc136674ee2d16b36453bd51ea575c32c0ba9b39"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.3.0/anchor_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "0bf601d3706a0227305cdbea53336d0807461d0d84cc6819bd0b0c86751d3ccd"

      def install
        bin.install "anchor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.3.0/anchor_0.3.0_Linux_armv6.tar.gz"
      sha256 "e3fc248771239996f33018272e1891ad0a1573a2c2bd1868a204d4f865240289"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.3.0/anchor_0.3.0_Linux_arm64.tar.gz"
      sha256 "7b69d9afdbba0d30580c8d141bb1a903a7191b88614f8c04ce2961b2945858e9"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.3.0/anchor_0.3.0_Linux_x86_64.tar.gz"
      sha256 "cd85c90c4f71d3e8b6fc528bfd9ea9a78fa5c74381e944317372976c77c95076"

      def install
        bin.install "anchor"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/anchor --version"
  end
end
