# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc "Dynamic versioned controlled remote marketplace for local / CI environments"
  homepage "https://ZachiNachshon.github.io/anchor/"
  version "1.0.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v1.0.0/anchor_1.0.0_Darwin_arm64.tar.gz"
      sha256 "46c4e3aa589b243fc647e1f185e1f1ab092193b59b794ef852d3347034c1a57d"
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v1.0.0/anchor_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "32be903774717712d48cc92df14853962402f6360e050e5f759734b8baea4613"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v1.0.0/anchor_1.0.0_Linux_armv6.tar.gz"
      sha256 "e78dfb9bb09472f3b1f5f0ab8d000f150555d2ec2ffad130d38a7f960eb93ff6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v1.0.0/anchor_1.0.0_Linux_arm64.tar.gz"
      sha256 "71968307d51fa2d27ef767c1863f0f6e88eba0a298a31d2278e943c3a9567721"
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v1.0.0/anchor_1.0.0_Linux_x86_64.tar.gz"
      sha256 "aa7a616f9ab8a51738921dd8759b3fcf822af9e238377575b271b4ec08cd029a"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  def install
    bin.install "anchor"
  end

  test do
    system "#{bin}/anchor --version"
  end
end
