# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc "Dynamic versioned controlled remote marketplace for local / CI environments"
  homepage "https://ZachiNachshon.github.io/anchor/"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.7.0/anchor_0.7.0_darwin_arm64.tar.gz"
      sha256 "3eeeef1e47d2638baf4eaaa85d26bc6ca64e97938f1aa6fc97c75c2a11dace84"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.7.0/anchor_0.7.0_darwin_amd64.tar.gz"
      sha256 "5bf956ebdd8d643abda4c6723e532728cf44305b6d9681803e0e9f2abf75ad1d"

      def install
        bin.install "anchor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.7.0/anchor_0.7.0_linux_armv6.tar.gz"
      sha256 "78ef6d89da7223c8c211a1cd5a22c294f163c874d3f06a3fe932d2597c19fa24"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.7.0/anchor_0.7.0_linux_arm64.tar.gz"
      sha256 "3a25bfe6a4276bd5d7f8146f36a93e79cac08489352f2a2343697d84b56ef126"

      def install
        bin.install "anchor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ZachiNachshon/anchor/releases/download/v0.7.0/anchor_0.7.0_linux_amd64.tar.gz"
      sha256 "2766d57ccfcb8b3438890ac989ea2bba8ba6151aced5ad29c9aced0e5353fe8f"

      def install
        bin.install "anchor"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  test do
    system "#{bin}/anchor --version"
  end
end
